name: Deploy Backend + Frontend to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'beta'

      - name: Build & Deploy API
        run: |
          gcloud builds submit ./backend --tag gcr.io/${{ secrets.GCP_PROJECT }}/invest-api --project=${{ secrets.GCP_PROJECT }}
          gcloud run deploy invest-api \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/invest-api \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --add-cloudsql-instances=${{secrets.INSTANCE_CONNECTION_NAME}} \
            --update-env-vars="DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}',
              DEBUG=${{ secrets.DEBUG }},
              ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }},
              DJANGO_SETTINGS_MODULE=${{secrets.DJANGO_SETTINGS_MODULE}},
              GCS_STATIC_BUCKET=${{secrets.GCS_STATIC_BUCKET}},
              GCS_MEDIA_BUCKET=${{ secrets.GCS_MEDIA_BUCKET }},
              DB_NAME=${{ secrets.DB_NAME }},
              DB_USER=${{ secrets.DB_USER}},
              DB_PASSWORD=${{ secrets.DB_PASSWORD}},
              DB_PORT=${{ secrets.DB_PORT}}"

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build & Deploy Frontend
        run: |
          gcloud builds submit ./frontend --tag gcr.io/${{ secrets.GCP_PROJECT }}/invest-ui --project=${{ secrets.GCP_PROJECT }}
          gcloud run deploy invest-ui \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/invest-ui \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --update-env-vars \
              DEBUG=${{ secrets.DEBUG }} \