apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: django-superuser
spec:
  template:
    spec:
      containers:
        - image: gcr.io/${{ secrets.GCP_PROJECT }}/invest-api
          command: [ "python" ]
          args: [ "app/backend/manage.py", "makesuperuser" ]
      serviceAccountName: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      timeoutSeconds: 600
